# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitpath <- function(x, y, family, local_search, max_nnz, lambda_step, lambda, alpha, intercept, random_intercept, eps, max_cd_iter, max_ls_iter, max_bls_iter, t_init, t_scale, max_pql_iter, active_set, active_set_count, sort, screen) {
    .Call(`_glmmsel_fitpath`, x, y, family, local_search, max_nnz, lambda_step, lambda, alpha, intercept, random_intercept, eps, max_cd_iter, max_ls_iter, max_bls_iter, t_init, t_scale, max_pql_iter, active_set, active_set_count, sort, screen)
}

